### PR TITLE
Fixing a handful of tests on Mac OS

### PR DESCRIPTION
**Pull request by 2-complex**
**os::canonicalize_ok_if_relative_path
os::canonicalize_ok_if_path_ends_in_dotdot**

...both do something like this:

A = current working directory
B = A with redirection appended
assert(canonicalize(B) == A)

What if A is not already canonical?  I think the place Mac OS puts its temp directories has a symlink in the path, and that's why these tests fail on mac.  I propose fixing by adding an extra call to canonicalize in the check, so it looks more like this:

A = current working directory
B = A with trivial redirection
assert(canonicalize(B) == canonicalize(A))

**os::canonicalize_ok_with_dotdot_if_paths_exist
os::canonicalize_ok_if_file_exists**

have the same issue as above, but the fix is slightly different.  Here, I'm adding an extra check that reads the file contents at the canonicalized path, the idea is that guard against canonicalize returning the same wrong answer in both places.

**os::remove_file_fails_if_node_is_a_directory**

I think what's happening here is: when you remove_file a directory on Mac, it gives a different error-type from other OS's.  Mac gives you a permissions error (this seems wrong to me, but that's what it does)  If I run this...

    use std::fs;

    fn main() -> std::io::Result<()> {
        fs::create_dir("stuff")?;
        fs::remove_file("stuff")?;
        Ok(())
    }

on rust-playground, I get:

    Error: Os { code: 21, kind: Other, message: "Is a directory" }

On my Mac, I get:

    Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

What I wrote fixes this by making the test amenable to the Mac error, but I definitely see a valid argument for changing the implementation to generate the non-mac error.  Let me know what you think : )

**os::canonicalize_fails_if_subpath_is_file**

I'm pretty sure is failing because the underlying standard fs call doesn't do the right thing.  I can verify by running this code:

    use std::fs;
    use std::io::prelude::*;
    
    fn main() -> std::io::Result<()> {
        fs::create_dir("stuff")?;
        let mut f = fs::File::create("stuff/thing")?;
        f.write_all(b"content")?;
        let path = fs::canonicalize("stuff/thing/../thing")?;
        println!("My new path {}", path.to_str().unwrap());
        Ok(())
    }

If I run that on the rust playground, I get an error.  If I run it on my mac, I get no error and it prints:

    My new path /Users/ptrethewey/source/fileexper/stuff/thing

Rust documentation (https://doc.rust-lang.org/std/fs/fn.canonicalize.html) says the function should error if "a non-final component in path is not a directory"

So, the fix I propose is to modify os::canonicalize so that it does what the rust docs say, by adding an explicit check that each partial path is a directory, and manufacture the right error.

### CODE REVIEW

**Comment by TheSven73** [comment]
Awesome stuff, thank you 2-Complex ! This is what I meant when I said that this crate isn't mature enough to exist on crates.io. For example, I have no idea what will happen on Windows !! In any event, your fixes will help make the crate more mature.

Two things:

1. most of these issues are "orthogonal", meaning the issues don't affect each other. So it's easiest if you could submit each test fix as a separate commit (within reason). This also allows us to merge the ones that look ok, and continue discussion with others.

2. we want the library to behave exactly like the underlying OS. So if things are different between Linux and MacOS, we should probably:
- in the library, use conditional compilation `#[cfg(unix)] / #[cfg(macos)]` to make it behave identical to the OS it's running on
- in the tests, use conditional compilation to check it's returning the right thing (e.g. error A on Linux, error B on MacOS)

**Comment by 2-complex** [comment]
> most of these issues are "orthogonal", meaning the issues don't affect each other. So it's easiest if you could submit each test fix as a separate commit (within reason).
No problem : )

**Comment by 2-complex** [comment]
> we want the library to behave exactly like the underlying OS

I'm not so sure.  Even the fake filesystem?  Even if there's a bug in std::fs?  It looks to me like std::fs::canonicalize on mac has a bug.  Should fake::canonicalize emulate that bug on mac?  Or should fake::canonicalize not match os::canonicalize in this case?

**Comment by TheSven73** [comment]
On both macos and linux, Rust calls an OS library function called `realpath`. You can see this here:
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs.rs#L1105

Except that `realpath` will behave differently on both platforms:
[macos version](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/realpath.3.html)
[linux version](https://man7.org/linux/man-pages/man3/realpath.3.html)

As you can see, only the Linux version talks about generating an error when a path component is not a directory. Macos makes no such claims.

And there are more differences. Linux will always return absolute names, whereas macos may, in some circumstances, return relative paths. And I'm sure there are more differences, if we look hard enough. The two OSes have an identically named library function which behaves slightly differently, and is expected, and documented, to do so.

Is that a bug in Rust? I don't think so. These are just subtle platform-dependent differences, which Rust isn't really expected to paper over.

We now know that the "real" fs will behave slightly differently, depending on the platform. Our "fake" fs should behave exactly the same. Conditional compilation makes sense. It is also possible to pass a flag to the fake fs to change its behaviour: linux, windows, macos, fuchsia, ... but I'm not sure if anyone would want to use this.

**Comment by TheSven73** [comment]
> Conditional compilation makes sense. It is also possible to pass a flag to the fake fs to change its behaviour: linux, windows, macos, fuchsia, ... but I'm not sure if anyone would want to use this.

This is a good question. Is this something that'd be useful to you? Or that you could see someone would use?

**Comment by 2-complex** [comment]
>> pass a flag to the fake fs to change its behaviour
> Is this something that'd be useful to you?

I can imagine a scenario where that would be useful : )  Suppose I'm working on my own project that uses the fake-filesystem to do tests.  And suppose I accidentally write a test that relies on the mac filesystem behavior.  My test passes on my mac, but fails on Linux.  I don't have a Linux machine at my desk, so I don't notice until my CI runs, and then, when I realize there's a broken test, I want to reproduce the test-failure locally, but again I can't because I don't have a linux machine at my desk.  If I have the flag you're describing, I could reproduce the test failure on my mac and debug it there.

**Comment by TheSven73** [comment]
True. If you feel it might be useful, then use a flag to change behaviour of the fake fs to linux, macos, windows, etc. This should be ok, as long as the default fakefs behaviour is what it's compiled on.

For example, if fakefs is created with the default constructor, we get macos behaviour if compiled on macos, linux behaviour if compiled on linux, etc.

**Comment by TheSven73** [comment]
Replaced by #5 #6 #7 #8 #9

**Pull request closed without merging**
